services:
  db:
    image: postgres:14
    container_name: etl_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/products_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: etl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  metabase:
    image: metabase/metabase:v0.57.5.1
    container_name: etl_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_HOST: db
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
    depends_on:
      - db

volumes:
  pgdata: